spring:
  http:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
server:
  port: 80
#  compression:
#    enabled: true
#    mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
#    min-response-size: 1024
